commonLabels:
  prometheus: default

prometheusOperator:
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
  nodeSelector:
    cloud.google.com/gke-nodepool: infra-pool

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    tolerations:
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule
    nodeSelector:
      cloud.google.com/gke-nodepool: infra-pool
    resources:
      limits:
        memory: 500Mi
      requests:
        memory: 300Mi
        cpu: 10m
  serviceMonitorSelector:
    matchLabels:
      prometheus: default
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - prometheus

kubeDns:
  enabled: true
kubeScheduler:
  enabled: false
coreDns:
  enabled: false
kubeControllerManager:
  enabled: false

grafana:
  adminPassword: qwerty123
  ingress:
    enabled: true
    hosts:
      - grafana.34.71.35.199.xip.io
    annotations: {
      kubernetes.io/ingress.class: nginx
    }
    path: /
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100